image: python:3.11

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - apt-get update -y
  - apt-get install curl
  - pip3 install poetry
  - poetry install

test:
  # We need dind (Docker-IN-Docker) for dockcross
  services:
    - name: "docker:20.10.17-dind"
      variables:
        WAIT_FOR_SERVICE_TCP_PORT: '2376'
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_DRIVER: overlay2 
  script:
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - apt-get install -y software-properties-common
    - apt-get update   
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
    - apt-get update && apt-get install -y docker-ce-cli 
    - make build-all
    - poetry run pytest
