image: python:3.11

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - apt-get update -y
  - apt-get install -y curl
  - pip3 install poetry
  - poetry install

stages:
  - prechecks
  - test

license:
  image: docker:latest
  stage: prechecks
  services:
    - name: "docker:dind"
  before_script: [] # We don't need to install our dependencies for this
  script: 
    # Use Google's `addlicence` to check for BSD-2-Clause license 
    # See: https://github.com/google/addlicense
    - docker run --platform=linux/amd64 -v ${PWD}:/src ghcr.io/google/addlicense -v -check -l BSD-2-Clause -c "ChipFlow" -s=only -ignore **/__init__.py **/*.py

lint:
  stage: prechecks
  script: make lint

test:
  stage: test
  script:
    - poetry run pytest

test-macos:
  stage: test
  tags:
    - saas-macos-medium-m1
  image: macos-12-xcode-14
  allow_failure: true
  before_script:
    - export HOMEBREW_NO_AUTO_UPDATE=1 # Auto-update takes 15min+
    - export HOMEBREW_NO_INSTALL_CLEANUP=1 # Cleanup slows us down, so we turn it off.
    - export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 # Don't update dependencies for speed.
    - rm '/opt/homebrew/bin/virtualenv' # Needed for brew install
    - brew install poetry
    - poetry install
  script:
    - poetry run pytest

