image: python:3.11

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - apt-get update -y
  - apt-get install curl
  - pip3 install poetry
  - poetry install

generate_rtlil:
  script:
    - poetry run python -m chipflow_examples.mpw5.sky130 --yowasp --gen-rtlil ${CI_PROJECT_DIR}/mpw5_soc.il
  artifacts:
    paths:
      - mpw5_soc.il
