[tool.poetry]
name = "chipflow-examples"
version = "0.0.0"
description = "ChipFlow examples for making chips!"
authors = ["Robert Taylor <rob.taylor@chipflow.io>"]
license = "BSD-2-Clause"
readme = "README.md"
packages = [{include = "example_socs"}]

[tool.poetry.dependencies]
python = "^3.9"
amaranth = { git = "https://github.com/amaranth-lang/amaranth.git" }
amaranth-soc = { git = "https://github.com/amaranth-lang/amaranthi-soc.git" }
amaranth-orchard = { git = "https://gitlab.com/ChipFlow/amaranth-orchard.git" }

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
