[tool.poetry]
name = "chipflow-examples"
version = "0.0.0"
description = "ChipFlow examples for making chips!"
authors = ["Robert Taylor <rob.taylor@chipflow.io>"]
license = "BSD-2-Clause"
packages = [{include = "my_design"}]

[tool.poetry.dependencies]
python = "^3.8"
chipflow-lib = { git = "https://gitlab.com/ChipFlow/chipflow-lib.git" }
ziglang = "^0.10.1.post1"
pyelftools = "^0.29"

[[tool.poetry.source]]
name = "chipflow-amaranth-vexriscv"
url = "https://gitlab.com/api/v4/projects/33096707/packages/pypi/simple"
priority = "primary"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pycodestyle = "^2.9.1"
autopep8 = "^2.0.0"

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
